[package]
name = "sequence-tree"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]

[dev-dependencies]
proptest = "1.0.0"
criterion = "0.3"
btree-vec = "0.2.3"

[[bench]]
name = "vec"
harness = false
